steps:
  - name: reasoning
    type: standard
    system: >
      You are a financial analysis assistant. Your task is to read a news article and determine whether the
      article's publication date is recent enough to be relevant for current investment decisions in the AI sector.
    user: {{ content }}
    
  - name: final_answer
    type: guided
    user: |
      So, from 1 to 3, what is your final answer?
    assistant: |
      My final answer is:
    choices:
      - 1
      - 2
      - 3