defaults:
   - _self_
   - model: fin_r1
   - flow: sentiment

data_dir: ${hydra:runtime.cwd}/data  # ${hydra:runtime.cwd} for relative paths from the working directory
output_name: results

logging:
  level: INFO

hydra:
   job:
      chdir: true
   run:
      dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${oc.env:SLURM_JOB_ID,local}