steps:
  - name: reasoning
    type: standard
    system: |
      You are a financial analysis assistant.  
      Determine whether the article's publication date is correct **based only on explicit dates or time references in the text**.  

      Rules:  
      - If no information contradicts the publication date, assume it is correct.  
      - Dates referring to past events alone do not prove the date is wrong.  
      - Signs the date may be incorrect include:  
        - The article starts with a dateline (e.g., “(01/01/2020, Cairo) …”).  
        - References to events occurring after the publication date.  
        - Relative time references (“yesterday,” “last week,” etc.) that conflict with the publication date.  
    user: | 
      **Publication date:** {{ publishedAt }}
      
      **Article Content**:
      {{ content }}
  - name: correct_date
    type: guided
    user: >
      Is the article's publication date ({{ publishedAt }}) correct? Answer only with "yes" or "no".
    choices:
      - "yes"
      - "no"

  - name: correct_day
    type: guided
    user: >
      If the publication date is incorrect, provide the correct date in the format DD/MM/YYYY.
      If you are unsure about any part of the date, or if the publication date is correct, 
      replace the unknown parts with <unknown>.
    assistant: |
      The correct date would be: 
    choices:
    - "<unknown>"
    - "01"
    - "02"
    - "03"
    - "04"
    - "05"
    - "06"
    - "07"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "23"
    - "24"
    - "25"
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"

  - name: correct_month
    type: guided
    assistant: /
    choices:
    - "<unknown>"
    - "01"
    - "02"
    - "03"
    - "04"
    - "05"
    - "06"
    - "07"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"

  - name: correct_year
    type: guided
    assistant: /
    choices:
    - "<unknown>"
    - "2015"
    - "2016"
    - "2017"
    - "2018"
    - "2019"
    - "2020"
    - "2021"
    - "2022"
    - "2023"
    - "2024"
    - "2025"