steps:
  - name: reasoning
    type: standard
    system: |
      You are a financial analysis assistant. Read the news article and determine whether the main event it describes:  
      - Happened in the past (before the publication date), or  
      - Is occurring today, or is ongoing/current.  
    user: | 
      **Publication date:** {{ publishedAt }}

      **Article Content**:
      {{ content }}
  - name: final_answer
    type: guided
    user: | 
      Is the article about an event that happened in the past? Answer only with "yes" or "no".
    choices:
    - "yes"
    - "no"