steps:
  - name: reasoning
    type: standard
    system: >
      You are a financial analysis assistant. Your task is to read a news article and determine whether it is likely to 
      have a positive, negative, or neutral impact on investments in companies involved in artificial intelligence. 
      Focus on how the events, sentiment, or developments described in the article could affect the financial outlook,
      investor sentiment, or market value of such companies.
    user: |
      {{ content }}
  - name: final_answer
    type: guided
    user: |
      What is the sentiment of this article? Is it positive, negative, or neutral?
    assistant: |
      The sentiment is: 
    choices:
      - positive
      - negative
      - neutral